sector_emojis = {
    "Financial Services": "💰",
    "Utilities": "⚡️",
    "Industrials": "🏭",
    "Communication Services": "📡",
    "Healthcare": "🩺",
    "Real Estate": "🏠",
    "Energy": "🛢️",
    "Consumer Cyclical": "🛍️",
    "Consumer Defensive": "🍞",
    "Technology": "💻",
    "Basic Materials": "⛏️"
}

industry_emojis = {
    "Healthcare Plans": "📋",
    "Oil & Gas Integrated": "🛢️",
    "Medical Distribution": "💊",
    "Oil & Gas E&P": "⛽️",
    "Health Information Services": "🧬",
    "Conglomerates": "🔗",
    "REIT - Hotel & Motel": "🏨",
    "Oil & Gas Midstream": "🚛",
    "Computer Hardware": "🖥️",
    "Personal Services": "💇‍♂️",
    "Aerospace & Defense": "✈️",
    "Insurance - Property & Casualty": "🏚️",
    "REIT - Residential": "🏘️",
    "Trucking": "🚚",
    "Engineering & Construction": "🧱",
    "Drug Manufacturers - General": "💊",
    "Apparel Retail": "👗",
    "Specialty Retail": "🛍️",
    "Railroads": "🚆",
    "Medical Care Facilities": "🏥",
    "Scientific & Technical Instruments": "🔬",
    "Resorts & Casinos": "🎰",
    "Security & Protection Services": "🛡️",
    "Industrial Distribution": "🏭",
    "Oil & Gas Refining & Marketing": "🛢️",
    "Lodging": "🛏️",
    "Insurance - Life": "📜",
    "Banks - Regional": "🏦",
    "Utilities - Regulated Water": "🚰",
    "Insurance Brokers": "🤝",
    "REIT - Diversified": "🏢",
    "Specialty Business Services": "🧩",
    "Restaurants": "🍽️",
    "Farm Products": "🌽",
    "Oil & Gas Equipment & Services": "🔧",
    "Entertainment": "🎭",
    "Specialty Chemicals": "⚗️",
    "Consulting Services": "🧠",
    "Pollution & Treatment Controls": "🌫️",
    "Information Technology Services": "🖱️",
    "Software - Infrastructure": "🧱",
    "Advertising Agencies": "📢",
    "Electrical Equipment & Parts": "💡",
    "Utilities - Renewable": "🌞",
    "Auto & Truck Dealerships": "🚗",
    "Footwear & Accessories": "👟",
    "Auto Parts": "🔩",
    "Banks - Diversified": "💳",
    "Auto Manufacturers": "🚘",
    "Waste Management": "🗑️",
    "Home Improvement Retail": "🛠️",
    "Beverages - Non-Alcoholic": "🥤",
    "Financial Data & Stock Exchanges": "📈",
    "REIT - Office": "🏬",
    "Software - Application": "📱",
    "Beverages - Brewers": "🍺",
    "Furnishings, Fixtures & Appliances": "🛋️",
    "Biotechnology": "🧫",
    "Copper": "🔩",
    "Travel Services": "✈️",
    "Utilities - Regulated Electric": "⚡️",
    "Telecom Services": "📞",
    "REIT - Industrial": "🏗️",
    "Internet Content & Information": "🌐",
    "Household & Personal Products": "🧼",
    "Insurance - Diversified": "🛡️",
    "Pharmaceutical Retailers": "💊",
    "Utilities - Diversified": "🔌",
    "Steel": "🔧",
    "REIT - Retail": "🏪",
    "Confectioners": "🍫",
    "Capital Markets": "🏛️",
    "Food Distribution": "🍎",
    "Apparel Manufacturing": "👕",
    "Residential Construction": "🚧",
    "Solar": "🔆",
    "Chemicals": "🧪",
    "Gold": "🥇",
    "Electronic Gaming & Multimedia": "🎮",
    "Building Products & Equipment": "🧰",
    "Asset Management": "📊",
    "Semiconductor Equipment & Materials": "💾",
    "Packaging & Containers": "📦",
    "Leisure": "🏖️",
    "Rental & Leasing Services": "📝",
    "Grocery Stores": "🛒",
    "REIT - Specialty": "🏢",
    "Tobacco": "🚬",
    "Tools & Accessories": "🔧",
    "Insurance - Reinsurance": "🔁",
    "Real Estate Services": "📐",
    "Farm & Heavy Construction Machinery": "🚜",
    "Utilities - Regulated Gas": "🔥",
    "Drug Manufacturers - Specialty & Generic": "🧪",
    "Specialty Industrial Machinery": "⚙️",
    "Semiconductors": "💻",
    "Building Materials": "🧱",
    "Internet Retail": "📦",
    "Utilities - Independent Power Producers": "🔋",
    "Medical Devices": "🦾",
    "Credit Services": "💳",
    "Packaged Foods": "🥫",
    "Discount Stores": "🏷️",
    "Agricultural Inputs": "🌾",
    "Airlines": "🛫",
    "REIT - Healthcare Facilities": "🏥",
    "Luxury Goods": "💎",
    "Medical Instruments & Supplies": "🩻",
    "Electronic Components": "📟",
    "Consumer Electronics": "📱",
    "Integrated Freight & Logistics": "📦",
    "Diagnostics & Research": "🔍",
    "Communication Equipment": "📡"
}

green_icon = '\U0001F7E2'

red_icon = '\U0001F534'